#!/bin/bash
export XDG_CONFIG_HOME=$HOME/.config
mkdir -p "$XDG_CONFIG_HOME/nixpkgs"
mkdir -p "$XDG_CONFIG_HOME"

#ln -sf "$(pwd)/nvim" "$XDG_CONFIG_HOME/nvim"

#ln -sf "$(pwd)/.zshrc" "$HOME/.zshrc"
#ln -sf "$(pwd)/.tmux.conf" "$HOME/.tmux.conf"
#ln -sf "$(pwd)/config.nix" "$XDG_CONFIG_HOME/nixpkgs/config.nix"
# Install Nix Packages from config.nix
nix-env -iA nixpkgs.myPackages
