#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

ln -sf "$(pwd)/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$(pwd)/.zshrc" "$HOME"/.zshrc
ln -sf "$(pwd)/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$(pwd)/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

wget -P "$HOME"/ https://raw.githubusercontent.com/bohleadam/dotfiles/refs/heads/main/zshrc/.zshrc


# Install Nix Packages from config.nix
nix-env -iA nixpkgs.myPackages
